// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmqzldojcpphcutmbco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbXF6bGRvamNwcGhjdXRtYmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjE1NDEsImV4cCI6MjA2MjAzNzU0MX0.p3OgyOQNobIWtw5FQqYZKgbKwXlUYzYWcAocuLK2CbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);